version: "3"

services:

    plex:
        image: linuxserver/plex
        expose: 
            - 32400
            - 33400
        network_mode: "host"
        volumes: 
            - '/mnt/gdrive:/gdrive:shared'
            - /home/arch/plex:/config
        depends_on:
            - rclone-mount
    
    rclone-mount:
        image: pablokbs/rclone-mount
        restart: unless-stopped
        ports:
            - '80:80'
        cap_add: 
            - SYS_ADMIN
        security_opt: 
            - 'apparmor:uconfined'
        volumes: 
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
            - '/home/arch/.config/rclone:/config'
            - '/mnt/gdrive:/mnt/mediaefs:shared'
        logging:
            options:
                max-size: 1g
        container_name: rclone-mount
        devices: 
            - /dev/fuse
        environment: 
            - 'RemotePath=team:'
            - 'MountCommands=--allow-other --allow-non-empty --buffer-size 256M'
            - 'ConfigName=rclone.conf'
    
